namespace Feliz.Isomorphic.Feliz

#if FABLE_COMPILER


type AriaDropEffect = Feliz.AriaDropEffect
type AriaRelevant = Feliz.AriaRelevant
type borderStyle = Feliz.borderStyle

module color =    
    let [<Literal>] indianRed = Feliz.color.indianRed
    let [<Literal>] lightCoral = Feliz.color.lightCoral
    let [<Literal>] salmon = Feliz.color.salmon
    let [<Literal>] darkSalmon = Feliz.color.darkSalmon
    let [<Literal>] lightSalmon = Feliz.color.lightSalmon
    let [<Literal>] crimson = Feliz.color.crimson
    let [<Literal>] red = Feliz.color.red
    let [<Literal>] fireBrick = Feliz.color.fireBrick
    let [<Literal>] darkRed = Feliz.color.darkRed
    let [<Literal>] pink = Feliz.color.pink
    let [<Literal>] lightPink = Feliz.color.lightPink
    let [<Literal>] hotPink = Feliz.color.hotPink
    let [<Literal>] deepPink = Feliz.color.deepPink
    let [<Literal>] mediumVioletRed = Feliz.color.mediumVioletRed
    let [<Literal>] paleVioletRed = Feliz.color.paleVioletRed
    let [<Literal>] coral = Feliz.color.coral
    let [<Literal>] tomato = Feliz.color.tomato
    let [<Literal>] orangeRed = Feliz.color.orangeRed
    let [<Literal>] darkOrange = Feliz.color.darkOrange
    let [<Literal>] orange = Feliz.color.orange
    let [<Literal>] gold = Feliz.color.gold
    let [<Literal>] yellow = Feliz.color.yellow
    let [<Literal>] lightYellow = Feliz.color.lightYellow
    let [<Literal>] limonChiffon = Feliz.color.limonChiffon
    let [<Literal>] lightGoldenRodYellow = Feliz.color.lightGoldenRodYellow
    let [<Literal>] papayaWhip = Feliz.color.papayaWhip
    let [<Literal>] moccasin = Feliz.color.moccasin
    let [<Literal>] peachPuff = Feliz.color.peachPuff
    let [<Literal>] paleGoldenRod = Feliz.color.paleGoldenRod
    let [<Literal>] khaki = Feliz.color.khaki
    let [<Literal>] darkKhaki = Feliz.color.darkKhaki
    let [<Literal>] lavender = Feliz.color.lavender
    let [<Literal>] thistle = Feliz.color.thistle
    let [<Literal>] plum = Feliz.color.plum
    let [<Literal>] violet = Feliz.color.violet
    let [<Literal>] orchid = Feliz.color.orchid
    let [<Literal>] fuchsia = Feliz.color.fuchsia
    let [<Literal>] magenta = Feliz.color.magenta
    let [<Literal>] mediumOrchid = Feliz.color.mediumOrchid
    let [<Literal>] mediumPurple = Feliz.color.mediumPurple
    let [<Literal>] rebeccaPurple = Feliz.color.rebeccaPurple
    let [<Literal>] blueViolet = Feliz.color.blueViolet
    let [<Literal>] darkViolet = Feliz.color.darkViolet
    let [<Literal>] darkOrchid = Feliz.color.darkOrchid
    let [<Literal>] darkMagenta = Feliz.color.darkMagenta
    let [<Literal>] purple = Feliz.color.purple
    let [<Literal>] indigo = Feliz.color.indigo
    let [<Literal>] slateBlue = Feliz.color.slateBlue
    let [<Literal>] darkSlateBlue = Feliz.color.darkSlateBlue
    let [<Literal>] mediumSlateBlue = Feliz.color.mediumSlateBlue
    let [<Literal>] greenYellow = Feliz.color.greenYellow
    let [<Literal>] chartreuse = Feliz.color.chartreuse
    let [<Literal>] lawnGreen = Feliz.color.lawnGreen
    let [<Literal>] lime = Feliz.color.lime
    let [<Literal>] limeGreen = Feliz.color.limeGreen
    let [<Literal>] paleGreen = Feliz.color.paleGreen
    let [<Literal>] lightGreen = Feliz.color.lightGreen
    let [<Literal>] mediumSpringGreen = Feliz.color.mediumSpringGreen
    let [<Literal>] springGreen = Feliz.color.springGreen
    let [<Literal>] mediumSeaGreen = Feliz.color.mediumSeaGreen
    let [<Literal>] seaGreen = Feliz.color.seaGreen
    let [<Literal>] forestGreen = Feliz.color.forestGreen
    let [<Literal>] green = Feliz.color.green
    let [<Literal>] darkGreen = Feliz.color.darkGreen
    let [<Literal>] yellowGreen = Feliz.color.yellowGreen
    let [<Literal>] oliveDrab = Feliz.color.oliveDrab
    let [<Literal>] olive = Feliz.color.olive
    let [<Literal>] darkOliveGreen = Feliz.color.darkOliveGreen
    let [<Literal>] mediumAquamarine = Feliz.color.mediumAquamarine
    let [<Literal>] darkSeaGreen = Feliz.color.darkSeaGreen
    let [<Literal>] lightSeaGreen = Feliz.color.lightSeaGreen
    let [<Literal>] darkCyan = Feliz.color.darkCyan
    let [<Literal>] teal = Feliz.color.teal
    let [<Literal>] aqua = Feliz.color.aqua
    let [<Literal>] cyan = Feliz.color.cyan
    let [<Literal>] lightCyan = Feliz.color.lightCyan
    let [<Literal>] paleTurqouise = Feliz.color.paleTurqouise
    let [<Literal>] aquaMarine = Feliz.color.aquaMarine
    let [<Literal>] turqouise = Feliz.color.turqouise
    let [<Literal>] mediumTurqouise = Feliz.color.mediumTurqouise
    let [<Literal>] darkTurqouise = Feliz.color.darkTurqouise
    let [<Literal>] cadetBlue = Feliz.color.cadetBlue
    let [<Literal>] steelBlue = Feliz.color.steelBlue
    let [<Literal>] lightSteelBlue = Feliz.color.lightSteelBlue
    let [<Literal>] powederBlue = Feliz.color.powederBlue
    let [<Literal>] lightBlue = Feliz.color.lightBlue
    let [<Literal>] skyBlue = Feliz.color.skyBlue
    let [<Literal>] lightSkyBlue = Feliz.color.lightSkyBlue
    let [<Literal>] deepSkyBlue = Feliz.color.deepSkyBlue
    let [<Literal>] dodgerBlue = Feliz.color.dodgerBlue
    let [<Literal>] cornFlowerBlue = Feliz.color.cornFlowerBlue
    let [<Literal>] royalBlue = Feliz.color.royalBlue
    let [<Literal>] blue = Feliz.color.blue
    let [<Literal>] mediumBlue = Feliz.color.mediumBlue
    let [<Literal>] darkBlue = Feliz.color.darkBlue
    let [<Literal>] navy = Feliz.color.navy
    let [<Literal>] midnightBlue = Feliz.color.midnightBlue
    let [<Literal>] cornSilk = Feliz.color.cornSilk
    let [<Literal>] blanchedAlmond = Feliz.color.blanchedAlmond
    let [<Literal>] bisque = Feliz.color.bisque
    let [<Literal>] navajoWhite = Feliz.color.navajoWhite
    let [<Literal>] wheat = Feliz.color.wheat
    let [<Literal>] burlyWood = Feliz.color.burlyWood
    let [<Literal>] tan = Feliz.color.tan
    let [<Literal>] rosyBrown = Feliz.color.rosyBrown
    let [<Literal>] sandyBrown = Feliz.color.sandyBrown
    let [<Literal>] goldenRod = Feliz.color.goldenRod
    let [<Literal>] darkGoldenRod = Feliz.color.darkGoldenRod
    let [<Literal>] peru = Feliz.color.peru
    let [<Literal>] chocolate = Feliz.color.chocolate
    let [<Literal>] saddleBrown = Feliz.color.saddleBrown
    let [<Literal>] sienna = Feliz.color.sienna
    let [<Literal>] brown = Feliz.color.brown
    let [<Literal>] maroon = Feliz.color.maroon
    let [<Literal>] white = Feliz.color.white
    let [<Literal>] snow = Feliz.color.snow
    let [<Literal>] honeyDew = Feliz.color.honeyDew
    let [<Literal>] mintCream = Feliz.color.mintCream
    let [<Literal>] azure = Feliz.color.azure
    let [<Literal>] aliceBlue = Feliz.color.aliceBlue
    let [<Literal>] ghostWhite = Feliz.color.ghostWhite
    let [<Literal>] whiteSmoke = Feliz.color.whiteSmoke
    let [<Literal>] seaShell = Feliz.color.seaShell
    let [<Literal>] beige = Feliz.color.beige
    let [<Literal>] oldLace = Feliz.color.oldLace
    let [<Literal>] floralWhite = Feliz.color.floralWhite
    let [<Literal>] ivory = Feliz.color.ivory
    let [<Literal>] antiqueWhite = Feliz.color.antiqueWhite
    let [<Literal>] linen = Feliz.color.linen
    let [<Literal>] lavenderBlush = Feliz.color.lavenderBlush
    let [<Literal>] mistyRose = Feliz.color.mistyRose
    let [<Literal>] gainsBoro = Feliz.color.gainsBoro
    let [<Literal>] lightGray = Feliz.color.lightGray
    let [<Literal>] silver = Feliz.color.silver
    let [<Literal>] darkGray = Feliz.color.darkGray
    let [<Literal>] gray = Feliz.color.gray
    let [<Literal>] dimGray = Feliz.color.dimGray
    let [<Literal>] lightSlateGray = Feliz.color.lightSlateGray
    let [<Literal>] slateGray = Feliz.color.slateGray
    let [<Literal>] darkSlateGray = Feliz.color.darkSlateGray
    let [<Literal>] black = Feliz.color.black
    let [<Literal>] transparent = Feliz.color.transparent

    let hsl = Feliz.color.hsl
    let rgb = Feliz.color.rgb
    let rgba = Feliz.color.rgba


module font =
    let [<Literal>] abadiMTCondensedLight = Feliz.font.abadiMTCondensedLight
    let [<Literal>] aharoni = Feliz.font.aharoni
    let [<Literal>] aharoniBold = Feliz.font.aharoniBold
    let [<Literal>] aldhabi = Feliz.font.aldhabi
    let [<Literal>] alternateGothic2BT = Feliz.font.alternateGothic2BT
    let [<Literal>] andaleMono = Feliz.font.andaleMono
    let [<Literal>] andalus = Feliz.font.andalus
    let [<Literal>] angsanaNew = Feliz.font.angsanaNew
    let [<Literal>] angsanaUPC = Feliz.font.angsanaUPC
    let [<Literal>] aparajita = Feliz.font.aparajita
    let [<Literal>] appleChancery = Feliz.font.appleChancery
    let [<Literal>] arabicTypesetting = Feliz.font.arabicTypesetting
    let [<Literal>] arial = Feliz.font.arial
    let [<Literal>] arialBlack = Feliz.font.arialBlack
    let [<Literal>] arialNarrow = Feliz.font.arialNarrow
    let [<Literal>] arialNova = Feliz.font.arialNova
    let [<Literal>] arialRoundedMTBold = Feliz.font.arialRoundedMTBold
    let [<Literal>] arnoldboecklin = Feliz.font.arnoldboecklin
    let [<Literal>] avantaGarde = Feliz.font.avantaGarde
    let [<Literal>] bahnschrift = Feliz.font.bahnschrift
    let [<Literal>] bahnschriftLight = Feliz.font.bahnschriftLight
    let [<Literal>] bahnschriftSemiBold = Feliz.font.bahnschriftSemiBold
    let [<Literal>] bahnschriftSemiLight = Feliz.font.bahnschriftSemiLight
    let [<Literal>] baskerville = Feliz.font.baskerville
    let [<Literal>] batang = Feliz.font.batang
    let [<Literal>] batangChe = Feliz.font.batangChe
    let [<Literal>] bigCaslon = Feliz.font.bigCaslon
    let [<Literal>] bizUDGothic = Feliz.font.bizUDGothic
    let [<Literal>] bizUDMinchoMedium = Feliz.font.bizUDMinchoMedium
    let [<Literal>] blippo = Feliz.font.blippo
    let [<Literal>] bodoniMT = Feliz.font.bodoniMT
    let [<Literal>] bookAntiqua = Feliz.font.bookAntiqua
    let [<Literal>] Bookman = Feliz.font.Bookman
    let [<Literal>] bradlyHand = Feliz.font.bradlyHand
    let [<Literal>] browalliaNew = Feliz.font.browalliaNew
    let [<Literal>] browalliaUPC = Feliz.font.browalliaUPC
    let [<Literal>] brushScriptMT = Feliz.font.brushScriptMT
    let [<Literal>] brushScriptStd = Feliz.font.brushScriptStd
    let [<Literal>] brushStroke = Feliz.font.brushStroke
    let [<Literal>] calibri = Feliz.font.calibri
    let [<Literal>] calibriLight = Feliz.font.calibriLight
    let [<Literal>] calistoMT = Feliz.font.calistoMT
    let [<Literal>] cambodian = Feliz.font.cambodian
    let [<Literal>] cambria = Feliz.font.cambria
    let [<Literal>] cambriaMath = Feliz.font.cambriaMath
    let [<Literal>] candara = Feliz.font.candara
    let [<Literal>] centuryGothic = Feliz.font.centuryGothic
    let [<Literal>] chalkDuster = Feliz.font.chalkDuster
    let [<Literal>] cherokee = Feliz.font.cherokee
    let [<Literal>] comicSans = Feliz.font.comicSans
    let [<Literal>] comicSansMS = Feliz.font.comicSansMS
    let [<Literal>] consolas = Feliz.font.consolas
    let [<Literal>] constantia = Feliz.font.constantia
    let [<Literal>] copperPlate = Feliz.font.copperPlate
    let [<Literal>] copperPlateGothicLight = Feliz.font.copperPlateGothicLight
    let [<Literal>] copperPlateGothicBold = Feliz.font.copperPlateGothicBold
    let [<Literal>] corbel = Feliz.font.corbel
    let [<Literal>] cordiaNew = Feliz.font.cordiaNew
    let [<Literal>] cordiaUPC = Feliz.font.cordiaUPC
    let [<Literal>] coronetScript = Feliz.font.coronetScript
    let [<Literal>] courier = Feliz.font.courier
    let [<Literal>] courierNew = Feliz.font.courierNew
    let [<Literal>] daunPenh = Feliz.font.daunPenh
    let [<Literal>] david = Feliz.font.david
    let [<Literal>] dengXian = Feliz.font.dengXian
    let [<Literal>] dfKaiSB = Feliz.font.dfKaiSB
    let [<Literal>] didot = Feliz.font.didot
    let [<Literal>] dilleniaUPC = Feliz.font.dilleniaUPC
    let [<Literal>] dokChampa = Feliz.font.dokChampa
    let [<Literal>] dotum = Feliz.font.dotum
    let [<Literal>] dotumChe = Feliz.font.dotumChe
    let [<Literal>] ebrima = Feliz.font.ebrima
    let [<Literal>] estrangeloEdessa = Feliz.font.estrangeloEdessa
    let [<Literal>] eucrosiaUPC = Feliz.font.eucrosiaUPC
    let [<Literal>] euphemia = Feliz.font.euphemia
    let [<Literal>] fangSong = Feliz.font.fangSong
    let [<Literal>] florence = Feliz.font.florence
    let [<Literal>] franklinGothicMedium = Feliz.font.franklinGothicMedium
    let [<Literal>] frankRuehl = Feliz.font.frankRuehl
    let [<Literal>] fressiaUPC = Feliz.font.fressiaUPC
    let [<Literal>] futara = Feliz.font.futara
    let [<Literal>] gabriola = Feliz.font.gabriola
    let [<Literal>] garamond = Feliz.font.garamond
    let [<Literal>] gautami = Feliz.font.gautami
    let [<Literal>] geneva = Feliz.font.geneva
    let [<Literal>] georgia = Feliz.font.georgia
    let [<Literal>] georgiaPro = Feliz.font.georgiaPro
    let [<Literal>] gillSans = Feliz.font.gillSans
    let [<Literal>] gillSansNova = Feliz.font.gillSansNova
    let [<Literal>] gisha = Feliz.font.gisha
    let [<Literal>] goudyOldStyle = Feliz.font.goudyOldStyle
    let [<Literal>] gulim = Feliz.font.gulim
    let [<Literal>] gulimChe = Feliz.font.gulimChe
    let [<Literal>] gungsuh = Feliz.font.gungsuh
    let [<Literal>] gungsuhChe = Feliz.font.gungsuhChe
    let [<Literal>] hebrew = Feliz.font.hebrew
    let [<Literal>] helvetica = Feliz.font.helvetica
    let [<Literal>] hoeflerText = Feliz.font.hoeflerText
    let [<Literal>] holoLensMDL2Assets = Feliz.font.holoLensMDL2Assets
    let [<Literal>] impact = Feliz.font.impact
    let [<Literal>] inkFree = Feliz.font.inkFree
    let [<Literal>] irisUPC = Feliz.font.irisUPC
    let [<Literal>] iskoolaPota = Feliz.font.iskoolaPota
    let [<Literal>] japanese = Feliz.font.japanese
    let [<Literal>] jasmineUPC = Feliz.font.jasmineUPC
    let [<Literal>] javaneseText = Feliz.font.javaneseText
    let [<Literal>] jazzLET = Feliz.font.jazzLET
    let [<Literal>] kaiTi = Feliz.font.kaiTi
    let [<Literal>] kalinga = Feliz.font.kalinga
    let [<Literal>] kartika = Feliz.font.kartika
    let [<Literal>] khmerUI = Feliz.font.khmerUI
    let [<Literal>] kodchiangUPC = Feliz.font.kodchiangUPC
    let [<Literal>] kokila = Feliz.font.kokila
    let [<Literal>] korean = Feliz.font.korean
    let [<Literal>] lao = Feliz.font.lao
    let [<Literal>] laoUI = Feliz.font.laoUI
    let [<Literal>] latha = Feliz.font.latha
    let [<Literal>] leelawadee = Feliz.font.leelawadee
    let [<Literal>] leelawadeeUI = Feliz.font.leelawadeeUI
    let [<Literal>] leelawadeeUISemilight = Feliz.font.leelawadeeUISemilight
    let [<Literal>] levenimMT = Feliz.font.levenimMT
    let [<Literal>] lilyUPC = Feliz.font.lilyUPC
    let [<Literal>] lucidaBright = Feliz.font.lucidaBright
    let [<Literal>] lucidaConsole = Feliz.font.lucidaConsole
    let [<Literal>] lucidaHandwriting = Feliz.font.lucidaHandwriting
    let [<Literal>] lucidaSans = Feliz.font.lucidaSans
    let [<Literal>] lucidaSansTypewriter = Feliz.font.lucidaSansTypewriter
    let [<Literal>] lucidaSansUnicode = Feliz.font.lucidaSansUnicode
    let [<Literal>] lucidaTypewriter = Feliz.font.lucidaTypewriter
    let [<Literal>] luminari = Feliz.font.luminari
    let [<Literal>] malgunGothic = Feliz.font.malgunGothic
    let [<Literal>] malgunGothicSemilight = Feliz.font.malgunGothicSemilight
    let [<Literal>] mangal = Feliz.font.mangal
    let [<Literal>] markerFelt = Feliz.font.markerFelt
    let [<Literal>] marlett = Feliz.font.marlett
    let [<Literal>] meiryo = Feliz.font.meiryo
    let [<Literal>] meiryoUI = Feliz.font.meiryoUI
    let [<Literal>] microsoftHimalaya = Feliz.font.microsoftHimalaya
    let [<Literal>] microsoftJhengHei = Feliz.font.microsoftJhengHei
    let [<Literal>] microsoftJhengHeiUI = Feliz.font.microsoftJhengHeiUI
    let [<Literal>] microsoftNewTaiLue = Feliz.font.microsoftNewTaiLue
    let [<Literal>] microsoftPhagsPa = Feliz.font.microsoftPhagsPa
    let [<Literal>] microsoftSansSerif = Feliz.font.microsoftSansSerif
    let [<Literal>] microsoftTaiLe = Feliz.font.microsoftTaiLe
    let [<Literal>] microsoftUighur = Feliz.font.microsoftUighur
    let [<Literal>] microsoftYaHei = Feliz.font.microsoftYaHei
    let [<Literal>] microsoftYaHeiUI = Feliz.font.microsoftYaHeiUI
    let [<Literal>] microsoftYiBaiti = Feliz.font.microsoftYiBaiti
    let [<Literal>] mingLiU = Feliz.font.mingLiU
    let [<Literal>] mingLiUHKSCS = Feliz.font.mingLiUHKSCS
    let [<Literal>] mingLiUHKSCSExtB = Feliz.font.mingLiUHKSCSExtB
    let [<Literal>] mingLiUExtB = Feliz.font.mingLiUExtB
    let [<Literal>] miriam = Feliz.font.miriam
    let [<Literal>] monaco = Feliz.font.monaco
    let [<Literal>] mongolianBaiti = Feliz.font.mongolianBaiti
    let [<Literal>] moolBoran = Feliz.font.moolBoran
    let [<Literal>] msGothic = Feliz.font.msGothic
    let [<Literal>] msMincho = Feliz.font.msMincho
    let [<Literal>] msPGothic = Feliz.font.msPGothic
    let [<Literal>] msPMincho = Feliz.font.msPMincho
    let [<Literal>] msUIGothic = Feliz.font.msUIGothic
    let [<Literal>] mvBoli = Feliz.font.mvBoli
    let [<Literal>] myanmarText = Feliz.font.myanmarText
    let [<Literal>] narkisim = Feliz.font.narkisim
    let [<Literal>] neueHaasGroteskTextPro = Feliz.font.neueHaasGroteskTextPro
    let [<Literal>] newCenturySchoolbook = Feliz.font.newCenturySchoolbook
    let [<Literal>] newsGothicMT = Feliz.font.newsGothicMT
    let [<Literal>] nirmalaUI = Feliz.font.nirmalaUI
    let [<Literal>] noAutoLanguageAssoc = Feliz.font.noAutoLanguageAssoc
    let [<Literal>] noto = Feliz.font.noto
    let [<Literal>] nSimSun = Feliz.font.nSimSun
    let [<Literal>] nyala = Feliz.font.nyala
    let [<Literal>] oldTown = Feliz.font.oldTown
    let [<Literal>] optima = Feliz.font.optima
    let [<Literal>] palatino = Feliz.font.palatino
    let [<Literal>] palatinoLinotype = Feliz.font.palatinoLinotype
    let [<Literal>] papyrus = Feliz.font.papyrus
    let [<Literal>] parkAvenue = Feliz.font.parkAvenue
    let [<Literal>] perpetua = Feliz.font.perpetua
    let [<Literal>] plantagenetCherokee = Feliz.font.plantagenetCherokee
    let [<Literal>] PMingLiU = Feliz.font.PMingLiU
    let [<Literal>] raavi = Feliz.font.raavi
    let [<Literal>] rockwell = Feliz.font.rockwell
    let [<Literal>] rockwellExtraBold = Feliz.font.rockwellExtraBold
    let [<Literal>] rockwellNova = Feliz.font.rockwellNova
    let [<Literal>] rockwellNovaCond = Feliz.font.rockwellNovaCond
    let [<Literal>] rockwellNovaExtraBold = Feliz.font.rockwellNovaExtraBold
    let [<Literal>] rod = Feliz.font.rod
    let [<Literal>] sakkalMajalla = Feliz.font.sakkalMajalla
    let [<Literal>] sanskritText = Feliz.font.sanskritText
    let [<Literal>] segoeMDL2Assets = Feliz.font.segoeMDL2Assets
    let [<Literal>] segoePrint = Feliz.font.segoePrint
    let [<Literal>] segoeScript = Feliz.font.segoeScript
    let [<Literal>] segoeUI = Feliz.font.segoeUI
    let [<Literal>] segoeUIEmoji = Feliz.font.segoeUIEmoji
    let [<Literal>] segoeUIHistoric = Feliz.font.segoeUIHistoric
    let [<Literal>] segoeUISymbol = Feliz.font.segoeUISymbol
    let [<Literal>] shonarBangla = Feliz.font.shonarBangla
    let [<Literal>] shruti = Feliz.font.shruti
    let [<Literal>] simHei = Feliz.font.simHei
    let [<Literal>] simKai = Feliz.font.simKai
    let [<Literal>] simplifiedArabic = Feliz.font.simplifiedArabic
    let [<Literal>] simplifiedChinese = Feliz.font.simplifiedChinese
    let [<Literal>] simSun = Feliz.font.simSun
    let [<Literal>] simSunExtB = Feliz.font.simSunExtB
    let [<Literal>] sitka = Feliz.font.sitka
    let [<Literal>] snellRoundhan = Feliz.font.snellRoundhan
    let [<Literal>] stencilStd = Feliz.font.stencilStd
    let [<Literal>] sylfaen = Feliz.font.sylfaen
    let [<Literal>] symbol = Feliz.font.symbol
    let [<Literal>] tahoma = Feliz.font.tahoma
    let [<Literal>] thai = Feliz.font.thai
    let [<Literal>] timesNewRoman = Feliz.font.timesNewRoman
    let [<Literal>] traditionalArabic = Feliz.font.traditionalArabic
    let [<Literal>] traditionalChinese = Feliz.font.traditionalChinese
    let [<Literal>] trattatello = Feliz.font.trattatello
    let [<Literal>] trebuchetMS = Feliz.font.trebuchetMS
    let [<Literal>] udDigiKyokasho = Feliz.font.udDigiKyokasho
    let [<Literal>] udDigiKyokashoNKR = Feliz.font.udDigiKyokashoNKR
    let [<Literal>] udDigiKyokashoNPR = Feliz.font.udDigiKyokashoNPR
    let [<Literal>] udDigiKyokashoNR = Feliz.font.udDigiKyokashoNR
    let [<Literal>] urduTypesetting = Feliz.font.urduTypesetting
    let [<Literal>] urwChancery = Feliz.font.urwChancery
    let [<Literal>] utsaah = Feliz.font.utsaah
    let [<Literal>] vani = Feliz.font.vani
    let [<Literal>] verdana = Feliz.font.verdana
    let [<Literal>] verdanaPro = Feliz.font.verdanaPro
    let [<Literal>] vijaya = Feliz.font.vijaya
    let [<Literal>] vrinda = Feliz.font.vrinda
    let [<Literal>] Webdings = Feliz.font.Webdings
    let [<Literal>] westminster = Feliz.font.westminster
    let [<Literal>] wingdings = Feliz.font.wingdings
    let [<Literal>] yuGothic = Feliz.font.yuGothic
    let [<Literal>] yuGothicUI = Feliz.font.yuGothicUI
    let [<Literal>] yuMincho = Feliz.font.yuMincho
    let [<Literal>] zapfChancery = Feliz.font.zapfChancery


type Html = Feliz.Html
type IKeyboardKey = Feliz.IKeyboardKey

module Interop =

    let reactApi = Feliz.Interop.reactApi
    let reactElement = Feliz.Interop.reactElement
    let mkAttr = Feliz.Interop.mkAttr
    let mkStyle = Feliz.Interop.mkStyle
    let reactElementWithChild = Feliz.Interop.reactElementWithChild
    let reactElementWithChildren = Feliz.Interop.reactElementWithChildren
    let createElement = Feliz.Interop.createElement

type IReactProperty = Feliz.IReactProperty
type IStyleAttribute = Feliz.IStyleAttribute

module key =

    let enter = Feliz.key.enter
    let one = Feliz.key.one
    let two = Feliz.key.two
    let three = Feliz.key.three
    let four = Feliz.key.four
    let five = Feliz.key.five
    let six = Feliz.key.six
    let seven = Feliz.key.seven
    let eight = Feliz.key.eight
    let nine = Feliz.key.nine
    let zero = Feliz.key.zero
    let backspace = Feliz.key.backspace
    let plus = Feliz.key.plus
    let minus = Feliz.key.minus
    let space = Feliz.key.space
    let tilde = Feliz.key.tilde
    let backtick = Feliz.key.backtick
    let a = Feliz.key.a
    let b = Feliz.key.b
    let c = Feliz.key.c
    let d = Feliz.key.d
    let e = Feliz.key.e
    let f = Feliz.key.f
    let g = Feliz.key.g
    let h = Feliz.key.h
    let i = Feliz.key.i
    let j = Feliz.key.j
    let k = Feliz.key.k
    let l = Feliz.key.l
    let m = Feliz.key.m
    let n = Feliz.key.n
    let o = Feliz.key.o
    let p = Feliz.key.p
    let q = Feliz.key.q
    let r = Feliz.key.r
    let s = Feliz.key.s
    let t = Feliz.key.t
    let u = Feliz.key.u
    let v = Feliz.key.v
    let w = Feliz.key.w
    let x = Feliz.key.x
    let y = Feliz.key.y
    let z = Feliz.key.z
    let ctrl = Feliz.key.ctrl
    let shift = Feliz.key.shift
    let ctrlAndShift = Feliz.key.ctrlAndShift

type length = Feliz.length
type prop = Feliz.prop

module prop =


    type allow = Feliz.prop.allow
    type ariaAutocomplete = Feliz.prop.ariaAutocomplete
    type ariaChecked = Feliz.prop.ariaChecked
    type ariaDropEffect = Feliz.prop.ariaDropEffect
    type ariaInvalid = Feliz.prop.ariaInvalid
    type ariaLive = Feliz.prop.ariaLive
    type ariaOrientation = Feliz.prop.ariaOrientation
    type ariaPressed = Feliz.prop.ariaPressed
    type ariaRelevant = Feliz.prop.ariaRelevant
    type ariaSort = Feliz.prop.ariaSort
    type as' = Feliz.prop.as'
    type autoCapitalize = Feliz.prop.autoCapitalize
    type charset = Feliz.prop.charset
    type coords = Feliz.prop.coords
    type crossOrigin = Feliz.prop.crossOrigin
    type dir = Feliz.prop.dir
    type dominantBaseline = Feliz.prop.dominantBaseline
    type httpEquiv = Feliz.prop.httpEquiv
    type inputMode = Feliz.prop.inputMode
    type kind = Feliz.prop.kind
    type preload = Feliz.prop.preload
    type referrerPolicy = Feliz.prop.referrerPolicy
    type rel = Feliz.prop.rel
    type role = Feliz.prop.role
    type selectionDirection = Feliz.prop.selectionDirection
    type shape = Feliz.prop.shape
    type target = Feliz.prop.target
    type textAnchor = Feliz.prop.textAnchor
    type transform = Feliz.prop.transform
    type type' = Feliz.prop.type'
type React = Feliz.React

module ReactApi =


    type IReactApi = Feliz.ReactApi.IReactApi
    type ReactChildren = Feliz.ReactApi.ReactChildren
type ReactDOM = Feliz.ReactDOM
type ReactDOMServer = Feliz.ReactDOMServer
type style = Feliz.style

module style =


    type alignContent = Feliz.style.alignContent
    type alignItems = Feliz.style.alignItems
    type alignSelf = Feliz.style.alignSelf
    type animationDirection = Feliz.style.animationDirection
    type animationFillMode = Feliz.style.animationFillMode
    type animationIterationCount = Feliz.style.animationIterationCount
    type animationPlayState = Feliz.style.animationPlayState
    type animationTimingFunction = Feliz.style.animationTimingFunction
    type backgroundBlendMode = Feliz.style.backgroundBlendMode
    type backgroundClip = Feliz.style.backgroundClip
    type backgroundColor = Feliz.style.backgroundColor
    type backgroundPosition = Feliz.style.backgroundPosition
    type backgroundRepeat = Feliz.style.backgroundRepeat
    type backgroundSize = Feliz.style.backgroundSize
    type borderCollapse = Feliz.style.borderCollapse
    type borderColor = Feliz.style.borderColor
    type borderStyle = Feliz.style.borderStyle
    type boxShadow = Feliz.style.boxShadow
    type color = Feliz.style.color
    type cursor = Feliz.style.cursor
    type direction = Feliz.style.direction
    type display = Feliz.style.display
    type emptyCells = Feliz.style.emptyCells
    type filter = Feliz.style.filter
    type flexBasis = Feliz.style.flexBasis
    type flexDirection = Feliz.style.flexDirection
    type flexWrap = Feliz.style.flexWrap
    type floatStyle = Feliz.style.floatStyle
    type fontKerning = Feliz.style.fontKerning
    type fontStretch = Feliz.style.fontStretch
    type fontStyle = Feliz.style.fontStyle
    type fontVariant = Feliz.style.fontVariant
    type fontWeight = Feliz.style.fontWeight
    type height = Feliz.style.height
    type justifyContent = Feliz.style.justifyContent
    type listStyleImage = Feliz.style.listStyleImage
    type listStylePosition = Feliz.style.listStylePosition
    type listStyleType = Feliz.style.listStyleType
    type margin = Feliz.style.margin
    type maxHeight = Feliz.style.maxHeight
    type minHeight = Feliz.style.minHeight
    type outlineStyle = Feliz.style.outlineStyle
    type outlineWidth = Feliz.style.outlineWidth
    type overflow = Feliz.style.overflow
    type overflowX = Feliz.style.overflowX
    type overflowY = Feliz.style.overflowY
    type position = Feliz.style.position
    type scrollBehavior = Feliz.style.scrollBehavior
    type tableLayout = Feliz.style.tableLayout
    type textAlign = Feliz.style.textAlign
    type textDecoration = Feliz.style.textDecoration
    type textDecorationColor = Feliz.style.textDecorationColor
    type textDecorationLine = Feliz.style.textDecorationLine
    type textDecorationStyle = Feliz.style.textDecorationStyle
    type textJustify = Feliz.style.textJustify
    type textOverflow = Feliz.style.textOverflow
    type textTransform = Feliz.style.textTransform
    type transform = Feliz.style.transform
    type transformStyle = Feliz.style.transformStyle
    type transitionTimingFunction = Feliz.style.transitionTimingFunction
    type userSelect = Feliz.style.userSelect
    type verticalAlign = Feliz.style.verticalAlign
    type visibility = Feliz.style.visibility
    type whitespace = Feliz.style.whitespace
    type wordBreak = Feliz.style.wordBreak
    type wordWrap = Feliz.style.wordWrap
    type writingMode = Feliz.style.writingMode
type IAlignContent = Feliz.Styles.IAlignContent
type IAlignItems = Feliz.Styles.IAlignItems
type IAlignSelf = Feliz.Styles.IAlignSelf
type IBackgroundClip = Feliz.Styles.IBackgroundClip
type IBackgroundRepeat = Feliz.Styles.IBackgroundRepeat
type IBorderStyle = Feliz.Styles.IBorderStyle
type ICssUnit = Feliz.Styles.ICssUnit
type IDisplay = Feliz.Styles.IDisplay
type IFontKerning = Feliz.Styles.IFontKerning
type IFontStretch = Feliz.Styles.IFontStretch
type IFontStyle = Feliz.Styles.IFontStyle
type IFontVariant = Feliz.Styles.IFontVariant
type IFontWeight = Feliz.Styles.IFontWeight
type IOverflow = Feliz.Styles.IOverflow
type IPosition = Feliz.Styles.IPosition
type ITextAlignment = Feliz.Styles.ITextAlignment
type ITextDecoration = Feliz.Styles.ITextDecoration
type ITextDecorationLine = Feliz.Styles.ITextDecorationLine
type ITransformProperty = Feliz.Styles.ITransformProperty
type ITransitionProperty = Feliz.Styles.ITransitionProperty
type IVisibility = Feliz.Styles.IVisibility
type IWordWrap = Feliz.Styles.IWordWrap
type textDecorationLine = Feliz.textDecorationLine
type textDecorationStyle = Feliz.textDecorationStyle
type transform = Feliz.transform
type transitionProperty = Feliz.transitionProperty
#else


type AnimationEvent = Feliz.ViewEngine.AnimationEvent
type AriaDropEffect = Feliz.ViewEngine.AriaDropEffect
type AriaRelevant = Feliz.ViewEngine.AriaRelevant
type ClipboardEvent = Feliz.ViewEngine.ClipboardEvent

module color =
    let [<Literal>] indianRed = Feliz.ViewEngine.color.indianRed
    let [<Literal>] lightCoral = Feliz.ViewEngine.color.lightCoral
    let [<Literal>] salmon = Feliz.ViewEngine.color.salmon
    let [<Literal>] darkSalmon = Feliz.ViewEngine.color.darkSalmon
    let [<Literal>] lightSalmon = Feliz.ViewEngine.color.lightSalmon
    let [<Literal>] crimson = Feliz.ViewEngine.color.crimson
    let [<Literal>] red = Feliz.ViewEngine.color.red
    let [<Literal>] fireBrick = Feliz.ViewEngine.color.fireBrick
    let [<Literal>] darkRed = Feliz.ViewEngine.color.darkRed
    let [<Literal>] pink = Feliz.ViewEngine.color.pink
    let [<Literal>] lightPink = Feliz.ViewEngine.color.lightPink
    let [<Literal>] hotPink = Feliz.ViewEngine.color.hotPink
    let [<Literal>] deepPink = Feliz.ViewEngine.color.deepPink
    let [<Literal>] mediumVioletRed = Feliz.ViewEngine.color.mediumVioletRed
    let [<Literal>] paleVioletRed = Feliz.ViewEngine.color.paleVioletRed
    let [<Literal>] coral = Feliz.ViewEngine.color.coral
    let [<Literal>] tomato = Feliz.ViewEngine.color.tomato
    let [<Literal>] orangeRed = Feliz.ViewEngine.color.orangeRed
    let [<Literal>] darkOrange = Feliz.ViewEngine.color.darkOrange
    let [<Literal>] orange = Feliz.ViewEngine.color.orange
    let [<Literal>] gold = Feliz.ViewEngine.color.gold
    let [<Literal>] yellow = Feliz.ViewEngine.color.yellow
    let [<Literal>] lightYellow = Feliz.ViewEngine.color.lightYellow
    let [<Literal>] limonChiffon = Feliz.ViewEngine.color.limonChiffon
    let [<Literal>] lightGoldenRodYellow = Feliz.ViewEngine.color.lightGoldenRodYellow
    let [<Literal>] papayaWhip = Feliz.ViewEngine.color.papayaWhip
    let [<Literal>] moccasin = Feliz.ViewEngine.color.moccasin
    let [<Literal>] peachPuff = Feliz.ViewEngine.color.peachPuff
    let [<Literal>] paleGoldenRod = Feliz.ViewEngine.color.paleGoldenRod
    let [<Literal>] khaki = Feliz.ViewEngine.color.khaki
    let [<Literal>] darkKhaki = Feliz.ViewEngine.color.darkKhaki
    let [<Literal>] lavender = Feliz.ViewEngine.color.lavender
    let [<Literal>] thistle = Feliz.ViewEngine.color.thistle
    let [<Literal>] plum = Feliz.ViewEngine.color.plum
    let [<Literal>] violet = Feliz.ViewEngine.color.violet
    let [<Literal>] orchid = Feliz.ViewEngine.color.orchid
    let [<Literal>] fuchsia = Feliz.ViewEngine.color.fuchsia
    let [<Literal>] magenta = Feliz.ViewEngine.color.magenta
    let [<Literal>] mediumOrchid = Feliz.ViewEngine.color.mediumOrchid
    let [<Literal>] mediumPurple = Feliz.ViewEngine.color.mediumPurple
    let [<Literal>] rebeccaPurple = Feliz.ViewEngine.color.rebeccaPurple
    let [<Literal>] blueViolet = Feliz.ViewEngine.color.blueViolet
    let [<Literal>] darkViolet = Feliz.ViewEngine.color.darkViolet
    let [<Literal>] darkOrchid = Feliz.ViewEngine.color.darkOrchid
    let [<Literal>] darkMagenta = Feliz.ViewEngine.color.darkMagenta
    let [<Literal>] purple = Feliz.ViewEngine.color.purple
    let [<Literal>] indigo = Feliz.ViewEngine.color.indigo
    let [<Literal>] slateBlue = Feliz.ViewEngine.color.slateBlue
    let [<Literal>] darkSlateBlue = Feliz.ViewEngine.color.darkSlateBlue
    let [<Literal>] mediumSlateBlue = Feliz.ViewEngine.color.mediumSlateBlue
    let [<Literal>] greenYellow = Feliz.ViewEngine.color.greenYellow
    let [<Literal>] chartreuse = Feliz.ViewEngine.color.chartreuse
    let [<Literal>] lawnGreen = Feliz.ViewEngine.color.lawnGreen
    let [<Literal>] lime = Feliz.ViewEngine.color.lime
    let [<Literal>] limeGreen = Feliz.ViewEngine.color.limeGreen
    let [<Literal>] paleGreen = Feliz.ViewEngine.color.paleGreen
    let [<Literal>] lightGreen = Feliz.ViewEngine.color.lightGreen
    let [<Literal>] mediumSpringGreen = Feliz.ViewEngine.color.mediumSpringGreen
    let [<Literal>] springGreen = Feliz.ViewEngine.color.springGreen
    let [<Literal>] mediumSeaGreen = Feliz.ViewEngine.color.mediumSeaGreen
    let [<Literal>] seaGreen = Feliz.ViewEngine.color.seaGreen
    let [<Literal>] forestGreen = Feliz.ViewEngine.color.forestGreen
    let [<Literal>] green = Feliz.ViewEngine.color.green
    let [<Literal>] darkGreen = Feliz.ViewEngine.color.darkGreen
    let [<Literal>] yellowGreen = Feliz.ViewEngine.color.yellowGreen
    let [<Literal>] oliveDrab = Feliz.ViewEngine.color.oliveDrab
    let [<Literal>] olive = Feliz.ViewEngine.color.olive
    let [<Literal>] darkOliveGreen = Feliz.ViewEngine.color.darkOliveGreen
    let [<Literal>] mediumAquamarine = Feliz.ViewEngine.color.mediumAquamarine
    let [<Literal>] darkSeaGreen = Feliz.ViewEngine.color.darkSeaGreen
    let [<Literal>] lightSeaGreen = Feliz.ViewEngine.color.lightSeaGreen
    let [<Literal>] darkCyan = Feliz.ViewEngine.color.darkCyan
    let [<Literal>] teal = Feliz.ViewEngine.color.teal
    let [<Literal>] aqua = Feliz.ViewEngine.color.aqua
    let [<Literal>] cyan = Feliz.ViewEngine.color.cyan
    let [<Literal>] lightCyan = Feliz.ViewEngine.color.lightCyan
    let [<Literal>] paleTurqouise = Feliz.ViewEngine.color.paleTurqouise
    let [<Literal>] aquaMarine = Feliz.ViewEngine.color.aquaMarine
    let [<Literal>] turqouise = Feliz.ViewEngine.color.turqouise
    let [<Literal>] mediumTurqouise = Feliz.ViewEngine.color.mediumTurqouise
    let [<Literal>] darkTurqouise = Feliz.ViewEngine.color.darkTurqouise
    let [<Literal>] cadetBlue = Feliz.ViewEngine.color.cadetBlue
    let [<Literal>] steelBlue = Feliz.ViewEngine.color.steelBlue
    let [<Literal>] lightSteelBlue = Feliz.ViewEngine.color.lightSteelBlue
    let [<Literal>] powederBlue = Feliz.ViewEngine.color.powederBlue
    let [<Literal>] lightBlue = Feliz.ViewEngine.color.lightBlue
    let [<Literal>] skyBlue = Feliz.ViewEngine.color.skyBlue
    let [<Literal>] lightSkyBlue = Feliz.ViewEngine.color.lightSkyBlue
    let [<Literal>] deepSkyBlue = Feliz.ViewEngine.color.deepSkyBlue
    let [<Literal>] dodgerBlue = Feliz.ViewEngine.color.dodgerBlue
    let [<Literal>] cornFlowerBlue = Feliz.ViewEngine.color.cornFlowerBlue
    let [<Literal>] royalBlue = Feliz.ViewEngine.color.royalBlue
    let [<Literal>] blue = Feliz.ViewEngine.color.blue
    let [<Literal>] mediumBlue = Feliz.ViewEngine.color.mediumBlue
    let [<Literal>] darkBlue = Feliz.ViewEngine.color.darkBlue
    let [<Literal>] navy = Feliz.ViewEngine.color.navy
    let [<Literal>] midnightBlue = Feliz.ViewEngine.color.midnightBlue
    let [<Literal>] cornSilk = Feliz.ViewEngine.color.cornSilk
    let [<Literal>] blanchedAlmond = Feliz.ViewEngine.color.blanchedAlmond
    let [<Literal>] bisque = Feliz.ViewEngine.color.bisque
    let [<Literal>] navajoWhite = Feliz.ViewEngine.color.navajoWhite
    let [<Literal>] wheat = Feliz.ViewEngine.color.wheat
    let [<Literal>] burlyWood = Feliz.ViewEngine.color.burlyWood
    let [<Literal>] tan = Feliz.ViewEngine.color.tan
    let [<Literal>] rosyBrown = Feliz.ViewEngine.color.rosyBrown
    let [<Literal>] sandyBrown = Feliz.ViewEngine.color.sandyBrown
    let [<Literal>] goldenRod = Feliz.ViewEngine.color.goldenRod
    let [<Literal>] darkGoldenRod = Feliz.ViewEngine.color.darkGoldenRod
    let [<Literal>] peru = Feliz.ViewEngine.color.peru
    let [<Literal>] chocolate = Feliz.ViewEngine.color.chocolate
    let [<Literal>] saddleBrown = Feliz.ViewEngine.color.saddleBrown
    let [<Literal>] sienna = Feliz.ViewEngine.color.sienna
    let [<Literal>] brown = Feliz.ViewEngine.color.brown
    let [<Literal>] maroon = Feliz.ViewEngine.color.maroon
    let [<Literal>] white = Feliz.ViewEngine.color.white
    let [<Literal>] snow = Feliz.ViewEngine.color.snow
    let [<Literal>] honeyDew = Feliz.ViewEngine.color.honeyDew
    let [<Literal>] mintCream = Feliz.ViewEngine.color.mintCream
    let [<Literal>] azure = Feliz.ViewEngine.color.azure
    let [<Literal>] aliceBlue = Feliz.ViewEngine.color.aliceBlue
    let [<Literal>] ghostWhite = Feliz.ViewEngine.color.ghostWhite
    let [<Literal>] whiteSmoke = Feliz.ViewEngine.color.whiteSmoke
    let [<Literal>] seaShell = Feliz.ViewEngine.color.seaShell
    let [<Literal>] beige = Feliz.ViewEngine.color.beige
    let [<Literal>] oldLace = Feliz.ViewEngine.color.oldLace
    let [<Literal>] floralWhite = Feliz.ViewEngine.color.floralWhite
    let [<Literal>] ivory = Feliz.ViewEngine.color.ivory
    let [<Literal>] antiqueWhite = Feliz.ViewEngine.color.antiqueWhite
    let [<Literal>] linen = Feliz.ViewEngine.color.linen
    let [<Literal>] lavenderBlush = Feliz.ViewEngine.color.lavenderBlush
    let [<Literal>] mistyRose = Feliz.ViewEngine.color.mistyRose
    let [<Literal>] gainsBoro = Feliz.ViewEngine.color.gainsBoro
    let [<Literal>] lightGray = Feliz.ViewEngine.color.lightGray
    let [<Literal>] silver = Feliz.ViewEngine.color.silver
    let [<Literal>] darkGray = Feliz.ViewEngine.color.darkGray
    let [<Literal>] gray = Feliz.ViewEngine.color.gray
    let [<Literal>] dimGray = Feliz.ViewEngine.color.dimGray
    let [<Literal>] lightSlateGray = Feliz.ViewEngine.color.lightSlateGray
    let [<Literal>] slateGray = Feliz.ViewEngine.color.slateGray
    let [<Literal>] darkSlateGray = Feliz.ViewEngine.color.darkSlateGray
    let [<Literal>] black = Feliz.ViewEngine.color.black
    let [<Literal>] transparent = Feliz.ViewEngine.color.transparent

    let hsl = Feliz.ViewEngine.color.hsl
    let rgb = Feliz.ViewEngine.color.rgb
    let rgba = Feliz.ViewEngine.color.rgba

type CompositionEvent = Feliz.ViewEngine.CompositionEvent
type DragEvent = Feliz.ViewEngine.DragEvent
type EraseAttribute = Feliz.ViewEngine.EraseAttribute
type Event = Feliz.ViewEngine.Event
type File = Feliz.ViewEngine.File
type FocusEvent = Feliz.ViewEngine.FocusEvent

module font =
    let [<Literal>] abadiMTCondensedLight = Feliz.ViewEngine.font.abadiMTCondensedLight
    let [<Literal>] aharoni = Feliz.ViewEngine.font.aharoni
    let [<Literal>] aharoniBold = Feliz.ViewEngine.font.aharoniBold
    let [<Literal>] aldhabi = Feliz.ViewEngine.font.aldhabi
    let [<Literal>] alternateGothic2BT = Feliz.ViewEngine.font.alternateGothic2BT
    let [<Literal>] andaleMono = Feliz.ViewEngine.font.andaleMono
    let [<Literal>] andalus = Feliz.ViewEngine.font.andalus
    let [<Literal>] angsanaNew = Feliz.ViewEngine.font.angsanaNew
    let [<Literal>] angsanaUPC = Feliz.ViewEngine.font.angsanaUPC
    let [<Literal>] aparajita = Feliz.ViewEngine.font.aparajita
    let [<Literal>] appleChancery = Feliz.ViewEngine.font.appleChancery
    let [<Literal>] arabicTypesetting = Feliz.ViewEngine.font.arabicTypesetting
    let [<Literal>] arial = Feliz.ViewEngine.font.arial
    let [<Literal>] arialBlack = Feliz.ViewEngine.font.arialBlack
    let [<Literal>] arialNarrow = Feliz.ViewEngine.font.arialNarrow
    let [<Literal>] arialNova = Feliz.ViewEngine.font.arialNova
    let [<Literal>] arialRoundedMTBold = Feliz.ViewEngine.font.arialRoundedMTBold
    let [<Literal>] arnoldboecklin = Feliz.ViewEngine.font.arnoldboecklin
    let [<Literal>] avantaGarde = Feliz.ViewEngine.font.avantaGarde
    let [<Literal>] bahnschrift = Feliz.ViewEngine.font.bahnschrift
    let [<Literal>] bahnschriftLight = Feliz.ViewEngine.font.bahnschriftLight
    let [<Literal>] bahnschriftSemiBold = Feliz.ViewEngine.font.bahnschriftSemiBold
    let [<Literal>] bahnschriftSemiLight = Feliz.ViewEngine.font.bahnschriftSemiLight
    let [<Literal>] baskerville = Feliz.ViewEngine.font.baskerville
    let [<Literal>] batang = Feliz.ViewEngine.font.batang
    let [<Literal>] batangChe = Feliz.ViewEngine.font.batangChe
    let [<Literal>] bigCaslon = Feliz.ViewEngine.font.bigCaslon
    let [<Literal>] bizUDGothic = Feliz.ViewEngine.font.bizUDGothic
    let [<Literal>] bizUDMinchoMedium = Feliz.ViewEngine.font.bizUDMinchoMedium
    let [<Literal>] blippo = Feliz.ViewEngine.font.blippo
    let [<Literal>] bodoniMT = Feliz.ViewEngine.font.bodoniMT
    let [<Literal>] bookAntiqua = Feliz.ViewEngine.font.bookAntiqua
    let [<Literal>] Bookman = Feliz.ViewEngine.font.Bookman
    let [<Literal>] bradlyHand = Feliz.ViewEngine.font.bradlyHand
    let [<Literal>] browalliaNew = Feliz.ViewEngine.font.browalliaNew
    let [<Literal>] browalliaUPC = Feliz.ViewEngine.font.browalliaUPC
    let [<Literal>] brushScriptMT = Feliz.ViewEngine.font.brushScriptMT
    let [<Literal>] brushScriptStd = Feliz.ViewEngine.font.brushScriptStd
    let [<Literal>] brushStroke = Feliz.ViewEngine.font.brushStroke
    let [<Literal>] calibri = Feliz.ViewEngine.font.calibri
    let [<Literal>] calibriLight = Feliz.ViewEngine.font.calibriLight
    let [<Literal>] calistoMT = Feliz.ViewEngine.font.calistoMT
    let [<Literal>] cambodian = Feliz.ViewEngine.font.cambodian
    let [<Literal>] cambria = Feliz.ViewEngine.font.cambria
    let [<Literal>] cambriaMath = Feliz.ViewEngine.font.cambriaMath
    let [<Literal>] candara = Feliz.ViewEngine.font.candara
    let [<Literal>] centuryGothic = Feliz.ViewEngine.font.centuryGothic
    let [<Literal>] chalkDuster = Feliz.ViewEngine.font.chalkDuster
    let [<Literal>] cherokee = Feliz.ViewEngine.font.cherokee
    let [<Literal>] comicSans = Feliz.ViewEngine.font.comicSans
    let [<Literal>] comicSansMS = Feliz.ViewEngine.font.comicSansMS
    let [<Literal>] consolas = Feliz.ViewEngine.font.consolas
    let [<Literal>] constantia = Feliz.ViewEngine.font.constantia
    let [<Literal>] copperPlate = Feliz.ViewEngine.font.copperPlate
    let [<Literal>] copperPlateGothicLight = Feliz.ViewEngine.font.copperPlateGothicLight
    let [<Literal>] copperPlateGothicBold = Feliz.ViewEngine.font.copperPlateGothicBold
    let [<Literal>] corbel = Feliz.ViewEngine.font.corbel
    let [<Literal>] cordiaNew = Feliz.ViewEngine.font.cordiaNew
    let [<Literal>] cordiaUPC = Feliz.ViewEngine.font.cordiaUPC
    let [<Literal>] coronetScript = Feliz.ViewEngine.font.coronetScript
    let [<Literal>] courier = Feliz.ViewEngine.font.courier
    let [<Literal>] courierNew = Feliz.ViewEngine.font.courierNew
    let [<Literal>] daunPenh = Feliz.ViewEngine.font.daunPenh
    let [<Literal>] david = Feliz.ViewEngine.font.david
    let [<Literal>] dengXian = Feliz.ViewEngine.font.dengXian
    let [<Literal>] dfKaiSB = Feliz.ViewEngine.font.dfKaiSB
    let [<Literal>] didot = Feliz.ViewEngine.font.didot
    let [<Literal>] dilleniaUPC = Feliz.ViewEngine.font.dilleniaUPC
    let [<Literal>] dokChampa = Feliz.ViewEngine.font.dokChampa
    let [<Literal>] dotum = Feliz.ViewEngine.font.dotum
    let [<Literal>] dotumChe = Feliz.ViewEngine.font.dotumChe
    let [<Literal>] ebrima = Feliz.ViewEngine.font.ebrima
    let [<Literal>] estrangeloEdessa = Feliz.ViewEngine.font.estrangeloEdessa
    let [<Literal>] eucrosiaUPC = Feliz.ViewEngine.font.eucrosiaUPC
    let [<Literal>] euphemia = Feliz.ViewEngine.font.euphemia
    let [<Literal>] fangSong = Feliz.ViewEngine.font.fangSong
    let [<Literal>] florence = Feliz.ViewEngine.font.florence
    let [<Literal>] franklinGothicMedium = Feliz.ViewEngine.font.franklinGothicMedium
    let [<Literal>] frankRuehl = Feliz.ViewEngine.font.frankRuehl
    let [<Literal>] fressiaUPC = Feliz.ViewEngine.font.fressiaUPC
    let [<Literal>] futara = Feliz.ViewEngine.font.futara
    let [<Literal>] gabriola = Feliz.ViewEngine.font.gabriola
    let [<Literal>] garamond = Feliz.ViewEngine.font.garamond
    let [<Literal>] gautami = Feliz.ViewEngine.font.gautami
    let [<Literal>] geneva = Feliz.ViewEngine.font.geneva
    let [<Literal>] georgia = Feliz.ViewEngine.font.georgia
    let [<Literal>] georgiaPro = Feliz.ViewEngine.font.georgiaPro
    let [<Literal>] gillSans = Feliz.ViewEngine.font.gillSans
    let [<Literal>] gillSansNova = Feliz.ViewEngine.font.gillSansNova
    let [<Literal>] gisha = Feliz.ViewEngine.font.gisha
    let [<Literal>] goudyOldStyle = Feliz.ViewEngine.font.goudyOldStyle
    let [<Literal>] gulim = Feliz.ViewEngine.font.gulim
    let [<Literal>] gulimChe = Feliz.ViewEngine.font.gulimChe
    let [<Literal>] gungsuh = Feliz.ViewEngine.font.gungsuh
    let [<Literal>] gungsuhChe = Feliz.ViewEngine.font.gungsuhChe
    let [<Literal>] hebrew = Feliz.ViewEngine.font.hebrew
    let [<Literal>] helvetica = Feliz.ViewEngine.font.helvetica
    let [<Literal>] hoeflerText = Feliz.ViewEngine.font.hoeflerText
    let [<Literal>] holoLensMDL2Assets = Feliz.ViewEngine.font.holoLensMDL2Assets
    let [<Literal>] impact = Feliz.ViewEngine.font.impact
    let [<Literal>] inkFree = Feliz.ViewEngine.font.inkFree
    let [<Literal>] irisUPC = Feliz.ViewEngine.font.irisUPC
    let [<Literal>] iskoolaPota = Feliz.ViewEngine.font.iskoolaPota
    let [<Literal>] japanese = Feliz.ViewEngine.font.japanese
    let [<Literal>] jasmineUPC = Feliz.ViewEngine.font.jasmineUPC
    let [<Literal>] javaneseText = Feliz.ViewEngine.font.javaneseText
    let [<Literal>] jazzLET = Feliz.ViewEngine.font.jazzLET
    let [<Literal>] kaiTi = Feliz.ViewEngine.font.kaiTi
    let [<Literal>] kalinga = Feliz.ViewEngine.font.kalinga
    let [<Literal>] kartika = Feliz.ViewEngine.font.kartika
    let [<Literal>] khmerUI = Feliz.ViewEngine.font.khmerUI
    let [<Literal>] kodchiangUPC = Feliz.ViewEngine.font.kodchiangUPC
    let [<Literal>] kokila = Feliz.ViewEngine.font.kokila
    let [<Literal>] korean = Feliz.ViewEngine.font.korean
    let [<Literal>] lao = Feliz.ViewEngine.font.lao
    let [<Literal>] laoUI = Feliz.ViewEngine.font.laoUI
    let [<Literal>] latha = Feliz.ViewEngine.font.latha
    let [<Literal>] leelawadee = Feliz.ViewEngine.font.leelawadee
    let [<Literal>] leelawadeeUI = Feliz.ViewEngine.font.leelawadeeUI
    let [<Literal>] leelawadeeUISemilight = Feliz.ViewEngine.font.leelawadeeUISemilight
    let [<Literal>] levenimMT = Feliz.ViewEngine.font.levenimMT
    let [<Literal>] lilyUPC = Feliz.ViewEngine.font.lilyUPC
    let [<Literal>] lucidaBright = Feliz.ViewEngine.font.lucidaBright
    let [<Literal>] lucidaConsole = Feliz.ViewEngine.font.lucidaConsole
    let [<Literal>] lucidaHandwriting = Feliz.ViewEngine.font.lucidaHandwriting
    let [<Literal>] lucidaSans = Feliz.ViewEngine.font.lucidaSans
    let [<Literal>] lucidaSansTypewriter = Feliz.ViewEngine.font.lucidaSansTypewriter
    let [<Literal>] lucidaSansUnicode = Feliz.ViewEngine.font.lucidaSansUnicode
    let [<Literal>] lucidaTypewriter = Feliz.ViewEngine.font.lucidaTypewriter
    let [<Literal>] luminari = Feliz.ViewEngine.font.luminari
    let [<Literal>] malgunGothic = Feliz.ViewEngine.font.malgunGothic
    let [<Literal>] malgunGothicSemilight = Feliz.ViewEngine.font.malgunGothicSemilight
    let [<Literal>] mangal = Feliz.ViewEngine.font.mangal
    let [<Literal>] markerFelt = Feliz.ViewEngine.font.markerFelt
    let [<Literal>] marlett = Feliz.ViewEngine.font.marlett
    let [<Literal>] meiryo = Feliz.ViewEngine.font.meiryo
    let [<Literal>] meiryoUI = Feliz.ViewEngine.font.meiryoUI
    let [<Literal>] microsoftHimalaya = Feliz.ViewEngine.font.microsoftHimalaya
    let [<Literal>] microsoftJhengHei = Feliz.ViewEngine.font.microsoftJhengHei
    let [<Literal>] microsoftJhengHeiUI = Feliz.ViewEngine.font.microsoftJhengHeiUI
    let [<Literal>] microsoftNewTaiLue = Feliz.ViewEngine.font.microsoftNewTaiLue
    let [<Literal>] microsoftPhagsPa = Feliz.ViewEngine.font.microsoftPhagsPa
    let [<Literal>] microsoftSansSerif = Feliz.ViewEngine.font.microsoftSansSerif
    let [<Literal>] microsoftTaiLe = Feliz.ViewEngine.font.microsoftTaiLe
    let [<Literal>] microsoftUighur = Feliz.ViewEngine.font.microsoftUighur
    let [<Literal>] microsoftYaHei = Feliz.ViewEngine.font.microsoftYaHei
    let [<Literal>] microsoftYaHeiUI = Feliz.ViewEngine.font.microsoftYaHeiUI
    let [<Literal>] microsoftYiBaiti = Feliz.ViewEngine.font.microsoftYiBaiti
    let [<Literal>] mingLiU = Feliz.ViewEngine.font.mingLiU
    let [<Literal>] mingLiUHKSCS = Feliz.ViewEngine.font.mingLiUHKSCS
    let [<Literal>] mingLiUHKSCSExtB = Feliz.ViewEngine.font.mingLiUHKSCSExtB
    let [<Literal>] mingLiUExtB = Feliz.ViewEngine.font.mingLiUExtB
    let [<Literal>] miriam = Feliz.ViewEngine.font.miriam
    let [<Literal>] monaco = Feliz.ViewEngine.font.monaco
    let [<Literal>] mongolianBaiti = Feliz.ViewEngine.font.mongolianBaiti
    let [<Literal>] moolBoran = Feliz.ViewEngine.font.moolBoran
    let [<Literal>] msGothic = Feliz.ViewEngine.font.msGothic
    let [<Literal>] msMincho = Feliz.ViewEngine.font.msMincho
    let [<Literal>] msPGothic = Feliz.ViewEngine.font.msPGothic
    let [<Literal>] msPMincho = Feliz.ViewEngine.font.msPMincho
    let [<Literal>] msUIGothic = Feliz.ViewEngine.font.msUIGothic
    let [<Literal>] mvBoli = Feliz.ViewEngine.font.mvBoli
    let [<Literal>] myanmarText = Feliz.ViewEngine.font.myanmarText
    let [<Literal>] narkisim = Feliz.ViewEngine.font.narkisim
    let [<Literal>] neueHaasGroteskTextPro = Feliz.ViewEngine.font.neueHaasGroteskTextPro
    let [<Literal>] newCenturySchoolbook = Feliz.ViewEngine.font.newCenturySchoolbook
    let [<Literal>] newsGothicMT = Feliz.ViewEngine.font.newsGothicMT
    let [<Literal>] nirmalaUI = Feliz.ViewEngine.font.nirmalaUI
    let [<Literal>] noAutoLanguageAssoc = Feliz.ViewEngine.font.noAutoLanguageAssoc
    let [<Literal>] noto = Feliz.ViewEngine.font.noto
    let [<Literal>] nSimSun = Feliz.ViewEngine.font.nSimSun
    let [<Literal>] nyala = Feliz.ViewEngine.font.nyala
    let [<Literal>] oldTown = Feliz.ViewEngine.font.oldTown
    let [<Literal>] optima = Feliz.ViewEngine.font.optima
    let [<Literal>] palatino = Feliz.ViewEngine.font.palatino
    let [<Literal>] palatinoLinotype = Feliz.ViewEngine.font.palatinoLinotype
    let [<Literal>] papyrus = Feliz.ViewEngine.font.papyrus
    let [<Literal>] parkAvenue = Feliz.ViewEngine.font.parkAvenue
    let [<Literal>] perpetua = Feliz.ViewEngine.font.perpetua
    let [<Literal>] plantagenetCherokee = Feliz.ViewEngine.font.plantagenetCherokee
    let [<Literal>] PMingLiU = Feliz.ViewEngine.font.PMingLiU
    let [<Literal>] raavi = Feliz.ViewEngine.font.raavi
    let [<Literal>] rockwell = Feliz.ViewEngine.font.rockwell
    let [<Literal>] rockwellExtraBold = Feliz.ViewEngine.font.rockwellExtraBold
    let [<Literal>] rockwellNova = Feliz.ViewEngine.font.rockwellNova
    let [<Literal>] rockwellNovaCond = Feliz.ViewEngine.font.rockwellNovaCond
    let [<Literal>] rockwellNovaExtraBold = Feliz.ViewEngine.font.rockwellNovaExtraBold
    let [<Literal>] rod = Feliz.ViewEngine.font.rod
    let [<Literal>] sakkalMajalla = Feliz.ViewEngine.font.sakkalMajalla
    let [<Literal>] sanskritText = Feliz.ViewEngine.font.sanskritText
    let [<Literal>] segoeMDL2Assets = Feliz.ViewEngine.font.segoeMDL2Assets
    let [<Literal>] segoePrint = Feliz.ViewEngine.font.segoePrint
    let [<Literal>] segoeScript = Feliz.ViewEngine.font.segoeScript
    let [<Literal>] segoeUI = Feliz.ViewEngine.font.segoeUI
    let [<Literal>] segoeUIEmoji = Feliz.ViewEngine.font.segoeUIEmoji
    let [<Literal>] segoeUIHistoric = Feliz.ViewEngine.font.segoeUIHistoric
    let [<Literal>] segoeUISymbol = Feliz.ViewEngine.font.segoeUISymbol
    let [<Literal>] shonarBangla = Feliz.ViewEngine.font.shonarBangla
    let [<Literal>] shruti = Feliz.ViewEngine.font.shruti
    let [<Literal>] simHei = Feliz.ViewEngine.font.simHei
    let [<Literal>] simKai = Feliz.ViewEngine.font.simKai
    let [<Literal>] simplifiedArabic = Feliz.ViewEngine.font.simplifiedArabic
    let [<Literal>] simplifiedChinese = Feliz.ViewEngine.font.simplifiedChinese
    let [<Literal>] simSun = Feliz.ViewEngine.font.simSun
    let [<Literal>] simSunExtB = Feliz.ViewEngine.font.simSunExtB
    let [<Literal>] sitka = Feliz.ViewEngine.font.sitka
    let [<Literal>] snellRoundhan = Feliz.ViewEngine.font.snellRoundhan
    let [<Literal>] stencilStd = Feliz.ViewEngine.font.stencilStd
    let [<Literal>] sylfaen = Feliz.ViewEngine.font.sylfaen
    let [<Literal>] symbol = Feliz.ViewEngine.font.symbol
    let [<Literal>] tahoma = Feliz.ViewEngine.font.tahoma
    let [<Literal>] thai = Feliz.ViewEngine.font.thai
    let [<Literal>] timesNewRoman = Feliz.ViewEngine.font.timesNewRoman
    let [<Literal>] traditionalArabic = Feliz.ViewEngine.font.traditionalArabic
    let [<Literal>] traditionalChinese = Feliz.ViewEngine.font.traditionalChinese
    let [<Literal>] trattatello = Feliz.ViewEngine.font.trattatello
    let [<Literal>] trebuchetMS = Feliz.ViewEngine.font.trebuchetMS
    let [<Literal>] udDigiKyokasho = Feliz.ViewEngine.font.udDigiKyokasho
    let [<Literal>] udDigiKyokashoNKR = Feliz.ViewEngine.font.udDigiKyokashoNKR
    let [<Literal>] udDigiKyokashoNPR = Feliz.ViewEngine.font.udDigiKyokashoNPR
    let [<Literal>] udDigiKyokashoNR = Feliz.ViewEngine.font.udDigiKyokashoNR
    let [<Literal>] urduTypesetting = Feliz.ViewEngine.font.urduTypesetting
    let [<Literal>] urwChancery = Feliz.ViewEngine.font.urwChancery
    let [<Literal>] utsaah = Feliz.ViewEngine.font.utsaah
    let [<Literal>] vani = Feliz.ViewEngine.font.vani
    let [<Literal>] verdana = Feliz.ViewEngine.font.verdana
    let [<Literal>] verdanaPro = Feliz.ViewEngine.font.verdanaPro
    let [<Literal>] vijaya = Feliz.ViewEngine.font.vijaya
    let [<Literal>] vrinda = Feliz.ViewEngine.font.vrinda
    let [<Literal>] Webdings = Feliz.ViewEngine.font.Webdings
    let [<Literal>] westminster = Feliz.ViewEngine.font.westminster
    let [<Literal>] wingdings = Feliz.ViewEngine.font.wingdings
    let [<Literal>] yuGothic = Feliz.ViewEngine.font.yuGothic
    let [<Literal>] yuGothicUI = Feliz.ViewEngine.font.yuGothicUI
    let [<Literal>] yuMincho = Feliz.ViewEngine.font.yuMincho
    let [<Literal>] zapfChancery = Feliz.ViewEngine.font.zapfChancery


type Html = Feliz.ViewEngine.Html
type IKeyboardKey = Feliz.ViewEngine.IKeyboardKey

module Interop =

    let mkText = Feliz.ViewEngine.Interop.mkText
    let reactElementWithChildren = Feliz.ViewEngine.Interop.reactElementWithChildren
    let reactElementWithChild = Feliz.ViewEngine.Interop.reactElementWithChild
    let createElement = Feliz.ViewEngine.Interop.createElement
    let createVoidElement = Feliz.ViewEngine.Interop.createVoidElement
    let createRawTextElement = Feliz.ViewEngine.Interop.createRawTextElement
    let createTextElement = Feliz.ViewEngine.Interop.createTextElement
    let mkAttr = Feliz.ViewEngine.Interop.mkAttr
    let mkStyle = Feliz.ViewEngine.Interop.mkStyle
    let mkChildren = Feliz.ViewEngine.Interop.mkChildren

type KeyboardEvent = Feliz.ViewEngine.KeyboardEvent
type length = Feliz.ViewEngine.length
type MouseEvent = Feliz.ViewEngine.MouseEvent
type prop = Feliz.ViewEngine.prop

module prop =


    type ariaAutocomplete = Feliz.ViewEngine.prop.ariaAutocomplete
    type ariaChecked = Feliz.ViewEngine.prop.ariaChecked
    type ariaDropEffect = Feliz.ViewEngine.prop.ariaDropEffect
    type ariaInvalid = Feliz.ViewEngine.prop.ariaInvalid
    type ariaLive = Feliz.ViewEngine.prop.ariaLive
    type ariaOrientation = Feliz.ViewEngine.prop.ariaOrientation
    type ariaPressed = Feliz.ViewEngine.prop.ariaPressed
    type ariaRelevant = Feliz.ViewEngine.prop.ariaRelevant
    type ariaSort = Feliz.ViewEngine.prop.ariaSort
    type as' = Feliz.ViewEngine.prop.as'
    type autoCapitalize = Feliz.ViewEngine.prop.autoCapitalize
    type charset = Feliz.ViewEngine.prop.charset
    type coords = Feliz.ViewEngine.prop.coords
    type crossOrigin = Feliz.ViewEngine.prop.crossOrigin
    type dir = Feliz.ViewEngine.prop.dir
    type dominantBaseline = Feliz.ViewEngine.prop.dominantBaseline
    type httpEquiv = Feliz.ViewEngine.prop.httpEquiv
    type inputMode = Feliz.ViewEngine.prop.inputMode
    type kind = Feliz.ViewEngine.prop.kind
    type preload = Feliz.ViewEngine.prop.preload
    type referrerPolicy = Feliz.ViewEngine.prop.referrerPolicy
    type rel = Feliz.ViewEngine.prop.rel
    type role = Feliz.ViewEngine.prop.role
    type selectionDirection = Feliz.ViewEngine.prop.selectionDirection
    type shape = Feliz.ViewEngine.prop.shape
    type target = Feliz.ViewEngine.prop.target
    type textAnchor = Feliz.ViewEngine.prop.textAnchor
    type transform = Feliz.ViewEngine.prop.transform
    type type' = Feliz.ViewEngine.prop.type'
type React = Feliz.ViewEngine.React
type ReactElement = Feliz.ViewEngine.ReactElement
type ReactProperty = Feliz.ViewEngine.ReactProperty
type Render = Feliz.ViewEngine.Render
type style = Feliz.ViewEngine.style

module style =


    type alignContent = Feliz.ViewEngine.style.alignContent
    type alignItems = Feliz.ViewEngine.style.alignItems
    type alignSelf = Feliz.ViewEngine.style.alignSelf
    type animationDirection = Feliz.ViewEngine.style.animationDirection
    type animationFillMode = Feliz.ViewEngine.style.animationFillMode
    type animationIterationCount = Feliz.ViewEngine.style.animationIterationCount
    type animationPlayState = Feliz.ViewEngine.style.animationPlayState
    type animationTimingFunction = Feliz.ViewEngine.style.animationTimingFunction
    type backgroundBlendMode = Feliz.ViewEngine.style.backgroundBlendMode
    type backgroundClip = Feliz.ViewEngine.style.backgroundClip
    type backgroundColor = Feliz.ViewEngine.style.backgroundColor
    type backgroundPosition = Feliz.ViewEngine.style.backgroundPosition
    type backgroundRepeat = Feliz.ViewEngine.style.backgroundRepeat
    type backgroundSize = Feliz.ViewEngine.style.backgroundSize
    type borderCollapse = Feliz.ViewEngine.style.borderCollapse
    type borderColor = Feliz.ViewEngine.style.borderColor
    type borderStyle = Feliz.ViewEngine.style.borderStyle
    type boxShadow = Feliz.ViewEngine.style.boxShadow
    type color = Feliz.ViewEngine.style.color
    type cursor = Feliz.ViewEngine.style.cursor
    type direction = Feliz.ViewEngine.style.direction
    type display = Feliz.ViewEngine.style.display
    type emptyCells = Feliz.ViewEngine.style.emptyCells
    type filter = Feliz.ViewEngine.style.filter
    type flexBasis = Feliz.ViewEngine.style.flexBasis
    type flexDirection = Feliz.ViewEngine.style.flexDirection
    type flexWrap = Feliz.ViewEngine.style.flexWrap
    type floatStyle = Feliz.ViewEngine.style.floatStyle
    type fontKerning = Feliz.ViewEngine.style.fontKerning
    type fontStretch = Feliz.ViewEngine.style.fontStretch
    type fontStyle = Feliz.ViewEngine.style.fontStyle
    type fontVariant = Feliz.ViewEngine.style.fontVariant
    type fontWeight = Feliz.ViewEngine.style.fontWeight
    type height = Feliz.ViewEngine.style.height
    type justifyContent = Feliz.ViewEngine.style.justifyContent
    type listStyleImage = Feliz.ViewEngine.style.listStyleImage
    type listStylePosition = Feliz.ViewEngine.style.listStylePosition
    type listStyleType = Feliz.ViewEngine.style.listStyleType
    type margin = Feliz.ViewEngine.style.margin
    type maxHeight = Feliz.ViewEngine.style.maxHeight
    type minHeight = Feliz.ViewEngine.style.minHeight
    type outlineStyle = Feliz.ViewEngine.style.outlineStyle
    type outlineWidth = Feliz.ViewEngine.style.outlineWidth
    type overflow = Feliz.ViewEngine.style.overflow
    type overflowX = Feliz.ViewEngine.style.overflowX
    type overflowY = Feliz.ViewEngine.style.overflowY
    type position = Feliz.ViewEngine.style.position
    type scrollBehavior = Feliz.ViewEngine.style.scrollBehavior
    type tableLayout = Feliz.ViewEngine.style.tableLayout
    type textAlign = Feliz.ViewEngine.style.textAlign
    type textDecoration = Feliz.ViewEngine.style.textDecoration
    type textDecorationColor = Feliz.ViewEngine.style.textDecorationColor
    type textDecorationLine = Feliz.ViewEngine.style.textDecorationLine
    type textDecorationStyle = Feliz.ViewEngine.style.textDecorationStyle
    type textJustify = Feliz.ViewEngine.style.textJustify
    type textOverflow = Feliz.ViewEngine.style.textOverflow
    type textTransform = Feliz.ViewEngine.style.textTransform
    type transform = Feliz.ViewEngine.style.transform
    type transformStyle = Feliz.ViewEngine.style.transformStyle
    type transitionTimingFunction = Feliz.ViewEngine.style.transitionTimingFunction
    type userSelect = Feliz.ViewEngine.style.userSelect
    type verticalAlign = Feliz.ViewEngine.style.verticalAlign
    type visibility = Feliz.ViewEngine.style.visibility
    type whitespace = Feliz.ViewEngine.style.whitespace
    type wordBreak = Feliz.ViewEngine.style.wordBreak
    type wordWrap = Feliz.ViewEngine.style.wordWrap
    type writingMode = Feliz.ViewEngine.style.writingMode
type CssUnit = Feliz.ViewEngine.Styles.CssUnit
type IAlignContent = Feliz.ViewEngine.Styles.IAlignContent
type IAlignItems = Feliz.ViewEngine.Styles.IAlignItems
type IAlignSelf = Feliz.ViewEngine.Styles.IAlignSelf
type IBackgroundClip = Feliz.ViewEngine.Styles.IBackgroundClip
type IBackgroundRepeat = Feliz.ViewEngine.Styles.IBackgroundRepeat
type IBorderStyle = Feliz.ViewEngine.Styles.IBorderStyle
type ICssUnit = Feliz.ViewEngine.Styles.ICssUnit
type IDisplay = Feliz.ViewEngine.Styles.IDisplay
type IFontKerning = Feliz.ViewEngine.Styles.IFontKerning
type IFontStretch = Feliz.ViewEngine.Styles.IFontStretch
type IFontStyle = Feliz.ViewEngine.Styles.IFontStyle
type IFontVariant = Feliz.ViewEngine.Styles.IFontVariant
type IFontWeight = Feliz.ViewEngine.Styles.IFontWeight
type IOverflow = Feliz.ViewEngine.Styles.IOverflow
type IPosition = Feliz.ViewEngine.Styles.IPosition
type IStyleAttribute = Feliz.ViewEngine.Styles.IStyleAttribute
type ITextAlignment = Feliz.ViewEngine.Styles.ITextAlignment
type ITextDecoration = Feliz.ViewEngine.Styles.ITextDecoration
type ITextDecorationLine = Feliz.ViewEngine.Styles.ITextDecorationLine
type ITransformProperty = Feliz.ViewEngine.Styles.ITransformProperty
type ITransitionProperty = Feliz.ViewEngine.Styles.ITransitionProperty
type IVisibility = Feliz.ViewEngine.Styles.IVisibility
type IWordWrap = Feliz.ViewEngine.Styles.IWordWrap
type StyleAttribute = Feliz.ViewEngine.Styles.StyleAttribute
type TextDecoration = Feliz.ViewEngine.Styles.TextDecoration
type TextDecorationLine = Feliz.ViewEngine.Styles.TextDecorationLine
type textDecorationLine = Feliz.ViewEngine.textDecorationLine
type textDecorationStyle = Feliz.ViewEngine.textDecorationStyle
type TouchEvent = Feliz.ViewEngine.TouchEvent
type TransitionEvent = Feliz.ViewEngine.TransitionEvent

module ViewBuilder =

    let getEscapeSequence = Feliz.ViewEngine.ViewBuilder.getEscapeSequence
    let escape = Feliz.ViewEngine.ViewBuilder.escape
    let buildXmlNode = Feliz.ViewEngine.ViewBuilder.buildXmlNode
    let buildHtmlNode = Feliz.ViewEngine.ViewBuilder.buildHtmlNode
    let buildXmlNodes = Feliz.ViewEngine.ViewBuilder.buildXmlNodes
    let buildHtmlNodes = Feliz.ViewEngine.ViewBuilder.buildHtmlNodes
    let buildHtmlDocument = Feliz.ViewEngine.ViewBuilder.buildHtmlDocument
    let buildXmlDocument = Feliz.ViewEngine.ViewBuilder.buildXmlDocument

type WheelEvent = Feliz.ViewEngine.WheelEvent
#endif